language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-sftp.gemspec
- gem install sensu-plugins-sftp-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: Tb1NSE8FqOOSNtrnBHuTczrCLIuBp0RFMS6d1TadVK1jX2J4hylovgTANqq58CFxyu5NTc80qBXPxDh9SR1w2o2c43aMVUKHjKAtDFjav8LztsoYBWoxEwqCd2uwo5e4kUQ15ybh3fXpyxVH8ce9CQYYXllFkZVKUSKXoPVxx/Q=
  gem: sensu-plugins-sftp
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-sftp
